DROP TABLE IF EXISTS ORDER_DETAILS;
CREATE TABLE ORDER_DETAILS(
ORDER_ID INTEGER(10) NOT NULL,
SKU VARCHAR(10) NOT NULL,
COST INTEGER(10) NOT NULL);

DROP TABLE IF EXISTS ORDER_RETAIL;
CREATE TABLE ORDER_RETAIL(
ORDER_ID INTEGER(10) NOT NULL,
SKU VARCHAR(10) NOT NULL,
RETAIL INTEGER(10) NOT NULL);